name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ['3.10', '3.11', '3.12']
    env:
      UV_PYTHON: ${{ matrix.py }}

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv sync
      - run: just check-all
